// Seed Fox Hollow Men's Club 2026 player roster into Convex
// Run with: node scripts/seed-players.mjs

const CONVEX_URL = "https://cheery-lemming-181.convex.cloud";

const players = [
  { name: "Abram, Jeff", handicapIndex: 13.4 },
  { name: "Adams, Clint", handicapIndex: 3.3 },
  { name: "Adams, Jason", handicapIndex: 13.0 },
  { name: "Alldredge, Shaun", handicapIndex: 1.9 },
  { name: "Alleman, David", handicapIndex: -1.7 },
  { name: "Allred, Alex", handicapIndex: 5.0 },
  { name: "Allred, Colin", handicapIndex: 11.9 },
  { name: "Allred, Steven", handicapIndex: null },
  { name: "Anae, Max", handicapIndex: null },
  { name: "Anderson, Brandon", handicapIndex: null },
  { name: "Anderson, Mike J", handicapIndex: 5.5 },
  { name: "Anderson, Steven", handicapIndex: 13.0 },
  { name: "Anderson, Trevor", handicapIndex: 2.7 },
  { name: "Argyle, Benjamin", handicapIndex: 4.5 },
  { name: "Argyle, Killian", handicapIndex: 18.0 },
  { name: "Argyle, Shawn", handicapIndex: 26.5 },
  { name: "Baldwin, Brad", handicapIndex: 7.3 },
  { name: "Ball, Jerald", handicapIndex: 36.0 },
  { name: "Barber, Dean", handicapIndex: 8.6 },
  { name: "Barth, Jason", handicapIndex: null },
  { name: "Bateman, Brigham", handicapIndex: 3.0 },
  { name: "Bateman, Chet", handicapIndex: 20.7 },
  { name: "Baxter, Zac", handicapIndex: null },
  { name: "Bayles, Scot", handicapIndex: 11.0 },
  { name: "Beaujeu, Jeff", handicapIndex: 10.1 },
  { name: "Beck, Randy", handicapIndex: null },
  { name: "Bell, Sam", handicapIndex: 13.3 },
  { name: "Bender, Daren", handicapIndex: 18.6 },
  { name: "Berry, Douglas", handicapIndex: 9.1 },
  { name: "Bezzant, Shawn", handicapIndex: 7.6 },
  { name: "Bleckert, Jace", handicapIndex: 12.5 },
  { name: "Brady, Zach", handicapIndex: 16.5 },
  { name: "Briem, Matthew", handicapIndex: 12.4 },
  { name: "Brooks, Jesse", handicapIndex: 13.4 },
  { name: "Brooksby, Kim", handicapIndex: null },
  { name: "Brown, Brian", handicapIndex: 28.1 },
  { name: "Brown, Jayton", handicapIndex: 5.0 },
  { name: "Brown, Mike", handicapIndex: 17.3 },
  { name: "Brown, Wes", handicapIndex: 2.1 },
  { name: "Bull, Douglas", handicapIndex: 22.2 },
  { name: "Bunker, Dick", handicapIndex: 9.1 },
  { name: "Bunker, Riley", handicapIndex: -1.0 },
  { name: "Burton, Jonathan", handicapIndex: 14.6 },
  { name: "Call, Alan", handicapIndex: 7.1 },
  { name: "Call, Eric", handicapIndex: null },
  { name: "Call, Mitch", handicapIndex: 1.6 },
  { name: "Call, Nathan", handicapIndex: 5.2 },
  { name: "Carter, Eric", handicapIndex: 14.7 },
  { name: "Carter, Jeff", handicapIndex: 19.4 },
  { name: "Carter, Robert", handicapIndex: 29.7 },
  { name: "Cattermole, Mark", handicapIndex: 8.9 },
  { name: "Chavez, Charles", handicapIndex: 4.2 },
  { name: "Chipman, Brady", handicapIndex: 29.9 },
  { name: "Chipman, Caden", handicapIndex: 7.0 },
  { name: "Chipman, Quentin", handicapIndex: 8.6 },
  { name: "Chipman, Shawn", handicapIndex: 10.2 },
  { name: "Christensen, Jon", handicapIndex: 11.4 },
  { name: "Clarine, David", handicapIndex: 26.1 },
  { name: "Clark, Daniel", handicapIndex: null },
  { name: "Clarke, Tyson", handicapIndex: 4.3 },
  { name: "Conger, Cameron", handicapIndex: 7.2 },
  { name: "Cook, Chantz", handicapIndex: null },
  { name: "Coombs, James", handicapIndex: 9.1 },
  { name: "Cox, Michael", handicapIndex: 11.5 },
  { name: "Crossley, Sam", handicapIndex: null },
  { name: "Crowley, Brian", handicapIndex: 23.2 },
  { name: "Darais, Danny", handicapIndex: 11.8 },
  { name: "David, Talan", handicapIndex: 6.5 },
  { name: "Davidson, Jordan", handicapIndex: null },
  { name: "Davis, Mike", handicapIndex: 4.1 },
  { name: "Davis, Ron", handicapIndex: 0.1 },
  { name: "Davis, Scott", handicapIndex: 7.9 },
  { name: "Dean, Randy", handicapIndex: 18.3 },
  { name: "Demille, Cameron", handicapIndex: 24.9 },
  { name: "Dent, Jett", handicapIndex: null },
  { name: "Dent, Scott", handicapIndex: null },
  { name: "Deveraux, Michael", handicapIndex: 7.4 },
  { name: "Douglass, Chad", handicapIndex: 2.8 },
  { name: "Draper, Abbey", handicapIndex: -2.7 },
  { name: "Draper, Jackson", handicapIndex: 9.9 },
  { name: "Dressel, Dustin", handicapIndex: 12.6 },
  { name: "Dunkley, Ryker", handicapIndex: -3.9 },
  { name: "Dunkley, Tyler", handicapIndex: null },
  { name: "Dunn, Colton", handicapIndex: 3.0 },
  { name: "Durrant, Roger", handicapIndex: null },
  { name: "Eakett, Jayden", handicapIndex: 3.4 },
  { name: "England, Nathan", handicapIndex: 30.1 },
  { name: "Ericksen, Lance", handicapIndex: 8.6 },
  { name: "Fairbanks, Scott", handicapIndex: 2.1 },
  { name: "Flinders, Tim", handicapIndex: 22.9 },
  { name: "Forbes, Chad", handicapIndex: 7.9 },
  { name: "Fox, Chad", handicapIndex: 3.1 },
  { name: "Fox, Scott", handicapIndex: 14.0 },
  { name: "Freeman, Kobe", handicapIndex: 16.8 },
  { name: "Freeman, Payton", handicapIndex: 12.6 },
  { name: "Freeman, Tom", handicapIndex: 7.9 },
  { name: "Frier, Jeff", handicapIndex: 10.6 },
  { name: "Garlick, Michael", handicapIndex: 16.8 },
  { name: "Garner, Cutter", handicapIndex: 10.2 },
  { name: "Goodwin, Steven", handicapIndex: 9.9 },
  { name: "Gordon, Kevin", handicapIndex: 8.8 },
  { name: "Gourley, Bob", handicapIndex: 10.3 },
  { name: "Gourley, Christopher", handicapIndex: 12.5 },
  { name: "Gourley, Scott", handicapIndex: 1.2 },
  { name: "Green, Doug", handicapIndex: 26.1 },
  { name: "Green, Roger", handicapIndex: 17.7 },
  { name: "Groesbeck, Ben", handicapIndex: null },
  { name: "Guzman, Agustin", handicapIndex: 5.4 },
  { name: "Hackford, Carl", handicapIndex: 15.9 },
  { name: "Hagen, Dalton", handicapIndex: 4.6 },
  { name: "Hale, Brandon", handicapIndex: 8.6 },
  { name: "Hale, Val", handicapIndex: 15.0 },
  { name: "Hales, Troy", handicapIndex: 17.5 },
  { name: "Halliday, Bryan", handicapIndex: 1.4 },
  { name: "Halliday, Corey", handicapIndex: 2.4 },
  { name: "Halliday, Greg", handicapIndex: 7.6 },
  { name: "Halliday, Jace", handicapIndex: 10.3 },
  { name: "Halliday, Ryan", handicapIndex: 1.4 },
  { name: "Halls, David", handicapIndex: 3.4 },
  { name: "Hansen, Spencer", handicapIndex: 18.0 },
  { name: "Hansen, Weston", handicapIndex: null },
  { name: "Hansgen, Brady", handicapIndex: 1.3 },
  { name: "Hansgen, Dan", handicapIndex: 9.3 },
  { name: "Hansgen, John", handicapIndex: 3.4 },
  { name: "Harding, Brandon", handicapIndex: 13.2 },
  { name: "Hardy, Jaxson", handicapIndex: 5.7 },
  { name: "Harley, Bob", handicapIndex: 16.4 },
  { name: "Hawkins, Mike", handicapIndex: 19.0 },
  { name: "Healy, Jon", handicapIndex: 9.8 },
  { name: "Healy, Scott", handicapIndex: 33.0 },
  { name: "Hemsley, Trevor", handicapIndex: 8.1 },
  { name: "Hendricks, William", handicapIndex: 0.5 },
  { name: "Herman, Bryant", handicapIndex: null },
  { name: "Herman, Jerid", handicapIndex: 6.3 },
  { name: "Herman, Jerry", handicapIndex: 26.5 },
  { name: "Hesterly, Bill", handicapIndex: 4.6 },
  { name: "Hicken, Kade", handicapIndex: 21.7 },
  { name: "Hicken, Randy", handicapIndex: -0.2 },
  { name: "Holdaway, Chad", handicapIndex: 19.1 },
  { name: "Holdaway, Ryan", handicapIndex: 16.5 },
  { name: "Holloway, Brian", handicapIndex: 17.0 },
  { name: "Huff, Jeffrey", handicapIndex: 17.4 },
  { name: "Humble, Tyler", handicapIndex: 15.3 },
  { name: "Hutchings, Jared", handicapIndex: 6.2 },
  { name: "Ivey, Shawn", handicapIndex: 17.5 },
  { name: "Jeppesen, Brock", handicapIndex: 6.2 },
  { name: "Johnson, Paul", handicapIndex: 5.2 },
  { name: "Joseph, Matthew", handicapIndex: 4.5 },
  { name: "Julkunen, Harry", handicapIndex: 6.7 },
  { name: "Julkunen, Mark", handicapIndex: 23.4 },
  { name: "Kallas, Caden", handicapIndex: 4.7 },
  { name: "Kasper, Mike", handicapIndex: 8.1 },
  { name: "Keetch, Darren", handicapIndex: null },
  { name: "Kelly, Ikaika", handicapIndex: 25.1 },
  { name: "Kelshaw, Dean", handicapIndex: null },
  { name: "Kenyon, Dallin", handicapIndex: 14.9 },
  { name: "Kenyon, Terry", handicapIndex: 6.7 },
  { name: "Knapp, Brett", handicapIndex: 13.5 },
  { name: "Kraus, Brent", handicapIndex: 20.5 },
  { name: "Lacey, Tanner", handicapIndex: 3.6 },
  { name: "Lambert, Gabe", handicapIndex: null },
  { name: "Lamoreaux, Richard", handicapIndex: 17.5 },
  { name: "Larsen, Nick", handicapIndex: 5.2 },
  { name: "Larsen, Thomas", handicapIndex: 3.7 },
  { name: "Larson, Shawn", handicapIndex: 6.5 },
  { name: "Lawson, Todd", handicapIndex: 8.5 },
  { name: "Loughton, Ben", handicapIndex: 20.5 },
  { name: "Lowe, Cooper", handicapIndex: null },
  { name: "Lowe, Mason", handicapIndex: 5.2 },
  { name: "Madsen, Shawn", handicapIndex: 9.6 },
  { name: "Manuela, Rawlin", handicapIndex: 16.6 },
  { name: "Marsh, Ryan", handicapIndex: null },
  { name: "Marsing, Chad", handicapIndex: 7.0 },
  { name: "Marsing, Noah", handicapIndex: null },
  { name: "Marsing, Tate", handicapIndex: null },
  { name: "Martinez, Tyler", handicapIndex: 4.0 },
  { name: "Mateer, Joshua", handicapIndex: 12.0 },
  { name: "Matthews, Kenny", handicapIndex: 12.0 },
  { name: "Maughan, Cameron", handicapIndex: 16.8 },
  { name: "Mayo, Kody", handicapIndex: 22.4 },
  { name: "McKeehan, Christopher", handicapIndex: 8.3 },
  { name: "McKeehan, Jack", handicapIndex: null },
  { name: "McMahan, Mike", handicapIndex: 12.5 },
  { name: "McNulty, Christopher", handicapIndex: 8.3 },
  { name: "Meier, Chris", handicapIndex: 8.1 },
  { name: "Miller, Cooper", handicapIndex: -0.5 },
  { name: "Miller, Jason", handicapIndex: 15.6 },
  { name: "Minnesota, Jake", handicapIndex: 6.0 },
  { name: "Mitchell, Jared", handicapIndex: 13.2 },
  { name: "Mitchell, Mark", handicapIndex: 17.1 },
  { name: "Morris, Randon", handicapIndex: 10.0 },
  { name: "Moulton, Ryan", handicapIndex: 5.2 },
  { name: "Nash, Glen", handicapIndex: 16.2 },
  { name: "Nelson, Jared", handicapIndex: 15.2 },
  { name: "Nielsen, Kenny", handicapIndex: 7.7 },
  { name: "Noftle, Fred", handicapIndex: 29.8 },
  { name: "Norton, Jon", handicapIndex: 4.9 },
  { name: "Orcutt, Ryan", handicapIndex: 13.0 },
  { name: "Owen, Kevin", handicapIndex: 8.8 },
  { name: "Pace, Brett", handicapIndex: 14.7 },
  { name: "Packer, Terry", handicapIndex: null },
  { name: "Parker, Randy", handicapIndex: 18.4 },
  { name: "Patrick, Laramie", handicapIndex: 11.5 },
  { name: "Paul, Josh", handicapIndex: 1.4 },
  { name: "Perkes, Brexton", handicapIndex: 6.7 },
  { name: "Peters, Payton", handicapIndex: 0.1 },
  { name: "Peters, Shaun", handicapIndex: 5.9 },
  { name: "Peterson, Jeff", handicapIndex: 11.5 },
  { name: "Pfister, Thomas", handicapIndex: 12.9 },
  { name: "Platt, Buckley", handicapIndex: 22.9 },
  { name: "Platt, David", handicapIndex: 4.0 },
  { name: "Pope, Jeff", handicapIndex: 10.3 },
  { name: "Porter, Jamen", handicapIndex: 5.7 },
  { name: "Prestwich, Bowen", handicapIndex: -2.8 },
  { name: "Price, Mason", handicapIndex: 28.2 },
  { name: "Quilter, Ryan", handicapIndex: 11.1 },
  { name: "Randall, Tyler", handicapIndex: 0.5 },
  { name: "Redd, Kelly", handicapIndex: 10.1 },
  { name: "Reese, Parker", handicapIndex: -2.7 },
  { name: "Reeve, Spencer", handicapIndex: 5.3 },
  { name: "Reeve, Stewart", handicapIndex: 2.4 },
  { name: "Richards, Cory", handicapIndex: 6.5 },
  { name: "Richards, Neil", handicapIndex: 6.5 },
  { name: "Richards, Preston", handicapIndex: -0.6 },
  { name: "Rickenbach, Jake", handicapIndex: 18.6 },
  { name: "Riddle, Kort", handicapIndex: 6.0 },
  { name: "Ridge, Anthony", handicapIndex: 9.1 },
  { name: "Risinger, Tim", handicapIndex: 6.4 },
  { name: "Roberts, Logan", handicapIndex: 0.9 },
  { name: "Ruffner, Bryon", handicapIndex: 11.3 },
  { name: "Sager, Andy", handicapIndex: 10.7 },
  { name: "Schetselaar, Derek", handicapIndex: 16.3 },
  { name: "Sederholm, Jared", handicapIndex: 20.1 },
  { name: "Seegmiller, Bradley", handicapIndex: 16.2 },
  { name: "Seymour, Dan", handicapIndex: 9.8 },
  { name: "Shepherdson, Robert", handicapIndex: 12.8 },
  { name: "Sherman, Austin", handicapIndex: null },
  { name: "Siebert, Samuel", handicapIndex: 26.4 },
  { name: "Smith, Brandon", handicapIndex: 28.1 },
  { name: "Smith, Brock", handicapIndex: 11.8 },
  { name: "Smith, Bryan", handicapIndex: 8.2 },
  { name: "Smith, Caden", handicapIndex: 19.7 },
  { name: "Smith, Cody", handicapIndex: null },
  { name: "Smith, Derek", handicapIndex: 29.8 },
  { name: "Smith, Kevin", handicapIndex: 9.3 },
  { name: "Smith, LaMar", handicapIndex: 12.5 },
  { name: "Smith, Paul", handicapIndex: 13.7 },
  { name: "Snarr, Camden", handicapIndex: null },
  { name: "Snyder, Stephen", handicapIndex: 13.3 },
  { name: "Sorenson, Kenneth", handicapIndex: null },
  { name: "Stevens, Laron", handicapIndex: 7.7 },
  { name: "Stevens, Matthew", handicapIndex: null },
  { name: "Stevenson, Sean", handicapIndex: 11.3 },
  { name: "Stewart, Andrew", handicapIndex: 5.1 },
  { name: "Storey, Swede", handicapIndex: 20.0 },
  { name: "Streetman, Damon", handicapIndex: 20.7 },
  { name: "Summerhays, Tom", handicapIndex: 10.9 },
  { name: "Sweat, Eric", handicapIndex: 19.3 },
  { name: "Tait, Adam", handicapIndex: -1.3 },
  { name: "Talbot, Tyler", handicapIndex: 9.1 },
  { name: "Tanaka, Keith", handicapIndex: null },
  { name: "Tanner, Kirk", handicapIndex: 12.1 },
  { name: "Taylor, Bryan", handicapIndex: 8.3 },
  { name: "Taylor, Jaxson", handicapIndex: -0.5 },
  { name: "Taylor, John", handicapIndex: null },
  { name: "Taylor, Justin", handicapIndex: null },
  { name: "Taylor, Michael", handicapIndex: 26.4 },
  { name: "Tea, Shane", handicapIndex: 18.1 },
  { name: "Templin, Scott", handicapIndex: 9.9 },
  { name: "Thomas, Emery", handicapIndex: -0.1 },
  { name: "Thornton, Cale", handicapIndex: 15.0 },
  { name: "Treu, Chandler", handicapIndex: -4.1 },
  { name: "Tripp, Andrew", handicapIndex: 15.5 },
  { name: "Tucker, Ben", handicapIndex: 13.7 },
  { name: "Tucker, Scott", handicapIndex: 17.8 },
  { name: "Tulip, Jacob", handicapIndex: 20.0 },
  { name: "Turner, Dallin", handicapIndex: 21.0 },
  { name: "Urry, Eric", handicapIndex: 15.9 },
  { name: "Valdivia, Jancarlos", handicapIndex: 36.0 },
  { name: "Valentine, G Scott", handicapIndex: 7.2 },
  { name: "Valentine, Gary", handicapIndex: 7.0 },
  { name: "Valerga, Brody", handicapIndex: 4.1 },
  { name: "VanPatten, Jake", handicapIndex: null },
  { name: "Vawdrey, Colton", handicapIndex: 6.9 },
  { name: "Walker, Dan", handicapIndex: 37.2 },
  { name: "Walker, Jackson", handicapIndex: 5.8 },
  { name: "Walker, Kim", handicapIndex: 7.1 },
  { name: "Walsh, Chris", handicapIndex: null },
  { name: "Warner, Aaron", handicapIndex: 18.2 },
  { name: "Watkins, Brady", handicapIndex: 4.1 },
  { name: "Watkins, Brett", handicapIndex: 9.1 },
  { name: "Watkins, Brock", handicapIndex: 13.0 },
  { name: "Watkins, Burke", handicapIndex: 6.6 },
  { name: "Weight, Mitch", handicapIndex: 4.2 },
  { name: "White, Noel", handicapIndex: 7.7 },
  { name: "White, Patrick", handicapIndex: 20.9 },
  { name: "Wilkin, Kalani", handicapIndex: 24.9 },
  { name: "Wilkins, Brandon", handicapIndex: 25.3 },
  { name: "Wilkins, Brent", handicapIndex: 12.3 },
  { name: "Willardson, Jeff", handicapIndex: 4.1 },
  { name: "Willes, David", handicapIndex: 10.1 },
  { name: "Williams, Brian", handicapIndex: null },
  { name: "Willis, Tyson", handicapIndex: 18.2 },
  { name: "Wilson, James", handicapIndex: 5.7 },
  { name: "Wilson, Michael", handicapIndex: 18.3 },
  { name: "Wilson, TravisMarc", handicapIndex: 8.5 },
  { name: "Wong, Louis", handicapIndex: 9.4 },
  { name: "Wootton, Nolan", handicapIndex: 26.4 },
  { name: "Workman, Hunter", handicapIndex: null },
  { name: "Workman, Regan", handicapIndex: 28.3 },
  { name: "Wray, Tyler", handicapIndex: 9.0 },
  { name: "Yates, Chad", handicapIndex: 7.9 },
  { name: "Yates, Gavin", handicapIndex: 20.8 },
  { name: "Yates, Lance", handicapIndex: null },
  { name: "Young, Rhett", handicapIndex: null },
  { name: "Young, Wayne", handicapIndex: 14.2 },
];

// Convert "Last, First" to "First Last"
function formatName(name) {
  const parts = name.split(", ");
  if (parts.length === 2) return `${parts[1]} ${parts[0]}`;
  return name;
}

async function createPlayer(player) {
  const body = {
    path: "players:create",
    args: [{
      name: formatName(player.name),
      ...(player.handicapIndex !== null ? { handicapIndex: player.handicapIndex } : {}),
    }],
  };

  const res = await fetch(`${CONVEX_URL}/api/mutation`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json();
  if (data.status === "success") {
    process.stdout.write(`✓ ${formatName(player.name)}\n`);
  } else {
    process.stdout.write(`✗ ${formatName(player.name)}: ${JSON.stringify(data)}\n`);
  }
}

console.log(`Seeding ${players.length} Fox Hollow players...\n`);
for (const player of players) {
  await createPlayer(player);
  await new Promise(r => setTimeout(r, 80));
}
console.log(`\nDone! ${players.length} players seeded.`);
